services:
  web:
    image: nginx:latest
    container_name: demo-web
    ports:
      - '8080:80'
    volumes:
      - $PWD/src:/var/www/html
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php-mssql:latest
    container_name: demo-php
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - $PWD/src:/var/www/html
    links:
      - mssql
    depends_on:
      - mssql

  mssql:
    image: mssql:2025
    container_name: demo-db
    build:
      context: mssql
      dockerfile: Dockerfile
    environment:
      MSSQL_SA_PASSWORD: "Sup3rStrongP@ssw0rd"
      MSSQL_COLLATION: "Latin1_General_100_CI_AS_SC_UTF8"
    ports:
      - '1433:1433'
